language: python
python: 3.5
env:
  matrix:
   - TOXENV=py35
   - TOXENV=flake8
install:
  - pip install tox
  - if test "$TOXENV" = py35 ; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py35 ; then coveralls ; fi
